name: Docker Install and Verify Lab

on:
  push:
    branches: [ "main" ]

jobs:
  docker-lab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Lab 2: Verification Step
      - name: Verify Docker Installation
        run: |
          echo "Checking if Docker is installed..."
          docker --version
          docker info | grep "Server Version"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lab-two:latest
